---
- name: taking backup of previous cmtmitro.sh
  become: yes
  become_user: mitro
  copy:
    src: /opt/application/mitro/cmt/cmtmitro.sh
    dest: "/opt/application/mitro/backup/cmtmitro.sh_{{ release_name }}"
    remote_src: yes

- name: removing previous cmtmitro.sh
  become: yes
  become_user: mitro
  file:
    path: /opt/application/mitro/cmt/cmtmitro.sh
    state: absent

- name: deploying new cmtmitro.sh
  become: yes
  become_user: mitro
  copy:
    src: "/opt/application/mitro/release/{{ release_name }}/{{ release_name }}_app/cmtmitro.sh"
    dest: /opt/application/mitro/cmt
    remote_src: yes

- name: changing permission of new cmtmitro.sh
  become: yes
  become_user: mitro
  file:
    path: /opt/application/mitro/cmt/cmtmitro.sh
    owner: mitro
    group: mitro
    mode: 0755

