---
- name: taking backup of previous emitro.war
  become: yes
  become_user: mitro
  copy:
    src: "{{ jboss_deployments }}/emitro.war"
    dest: "/opt/application/mitro/backup/emitro.war_{{ release_name }}"
    remote_src: yes

- name: removing previous emitro.war
  become: yes
  become_user: mitro
  file:
    path: "{{ jboss_deployments }}/emitro.war"
    state: absent

- name: deploying new emitro.war
  become: yes
  become_user: mitro
  copy:
    src: "/opt/application/mitro/release/{{ release_name }}/{{ release_name }}_app/emitro.war"
    dest: "{{ jboss_deployments }}"
    remote_src: yes

- name: changing permission of new emitro.war
  become: yes
  become_user: mitro
  file:
    path: "{{ jboss_deployments }}/emitro.war"
    owner: mitro
    group: mitro
    mode: 0775

